packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

variable "credentials_file" {
  type    = string
  default = "${env("credentials_file")}"
}

variable "environment" {
  type    = string
  default = "${env("environment")}"
}

variable "project_id" {
  type    = string
  default = "${env("project_id")}"
}

variable "zone" {
  type    = string
  default = "${env("zone")}"
}

source "googlecompute" "autogenerated_1" {
  account_file        = "${var.credentials_file}"
  image_name          = "observatory-image-${var.environment}"
  machine_type        = "n1-standard-1"
  project_id          = "${var.project_id}"
  source_image_family = "ubuntu-2204-lts"
  ssh_username        = "packer"
  zone                = "${var.zone}"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    inline = ["mkdir -p /tmp/opt/observatory/build"]
  }

  provisioner "file" {
    destination = "/tmp/opt"
    source      = "../packages"
  }

  provisioner "file" {
    destination = "/tmp/opt/observatory/build"
    source      = "../docker"
  }

  provisioner "shell" {
    script = "build.sh"
  }

}
