"""
    Observatory API

    The REST API for managing and accessing data from the Observatory Platform.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""

import datetime
import unittest

from observatory.api.client.exceptions import ApiTypeError, ApiAttributeError
from observatory.api.client.model.organisation import Organisation
from observatory.api.client.model.telescope import Telescope
from observatory.api.client.model.telescope_type import TelescopeType


class TestTelescope(unittest.TestCase):
    """Telescope unit test stubs"""

    def testTelescope(self):
        """Test Telescope"""

        # Create valid object
        dt = datetime.datetime.utcnow()
        Telescope(id=1,
                  organisation=Organisation(id=1,
                                            name='Curtin',
                                            gcp_project_id='my-gcp-project',
                                            gcp_download_bucket='my-download-bucket',
                                            gcp_transform_bucket='my-transform-bucket',
                                            created=dt,
                                            modified=dt),
                  telescope_type=TelescopeType(id=1,
                                               name='ONIX Telescope'),
                  created=dt,
                  modified=dt)

        # Invalid argument
        with self.assertRaises(ApiTypeError):
            Telescope('hello')

        # Invalid keyword argument
        with self.assertRaises(ApiAttributeError):
            Telescope(hello='world')


if __name__ == '__main__':
    unittest.main()
