"""
    Observatory API

    The REST API for managing and accessing data from the Observatory Platform.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""


import unittest
import datetime

from observatory.api.client.model.table_type import TableType
from observatory.api.client.exceptions import ApiAttributeError, ApiTypeError


class TestTableType(unittest.TestCase):
    """TableType unit test stubs"""

    def testTableType(self):
        """Test TableType"""

        class Configuration:
            def __init__(self):
                self.discard_unknown_keys = True

        # Create valid object
        type_id = "tabletype"
        name = "My table type"
        dt = datetime.datetime.utcnow()
        TableType(
            id=1,
            type_id=type_id,
            name=name,
            _configuration=Configuration(),
            unknown="var",
        )

        self.assertRaises(
            ApiAttributeError, TableType, id=1, type_id=type_id, name=name, created=dt, modified=dt
        )

        # Invalid argument
        with self.assertRaises(ApiTypeError):
            TableType("hello")

        # Invalid keyword argument
        with self.assertRaises(ApiAttributeError):
            TableType(hello="world")

        self.assertRaises(ApiTypeError, TableType._from_openapi_data, "hello")

        TableType._from_openapi_data(hello="world", _configuration=Configuration())


if __name__ == '__main__':
    unittest.main()
