"""
    Observatory API

    The REST API for managing and accessing data from the Observatory Platform.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""

import datetime
import unittest

from observatory.api.client.exceptions import ApiTypeError, ApiAttributeError
from observatory.api.client.model.organisation import Organisation


class TestOrganisation(unittest.TestCase):
    """Organisation unit test stubs"""

    def testOrganisation(self):
        """Test Organisation"""

        # Create valid object
        dt = datetime.datetime.utcnow()
        Organisation(
            id=1,
            name="Curtin",
            gcp_project_id="my-gcp-project",
            gcp_download_bucket="my-download-bucket",
            gcp_transform_bucket="my-transform-bucket",
            created=dt,
            modified=dt,
        )

        # Invalid argument
        with self.assertRaises(ApiTypeError):
            Organisation("hello")

        # Invalid keyword argument
        with self.assertRaises(ApiAttributeError):
            Organisation(hello="world")


if __name__ == "__main__":
    unittest.main()
