"""
    Observatory API

    The REST API for managing and accessing data from the Observatory Platform.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""

import datetime
import unittest

from observatory.api.client.exceptions import ApiTypeError, ApiAttributeError
from observatory.api.client.model.telescope_type import TelescopeType


class TestTelescopeType(unittest.TestCase):
    """TelescopeType unit test stubs"""

    def testTelescopeType(self):
        """Test TelescopeType"""

        # Create valid object
        dt = datetime.datetime.utcnow()
        TelescopeType(id=1,
                      name='ONIX Telescope',
                      created=dt,
                      modified=dt)

        # Invalid argument
        with self.assertRaises(ApiTypeError):
            TelescopeType('hello')

        # Invalid keyword argument
        with self.assertRaises(ApiAttributeError):
            TelescopeType(hello='world')


if __name__ == '__main__':
    unittest.main()
