# Copyright 2020 Curtin University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Tuan Chien

FROM python:3.9-slim

ARG HOST_USER_ID
ARG OBSERVATORY_HOME=/opt/observatory
ARG INSTALL_USER=apiserver

RUN adduser ${INSTALL_USER}
USER root
RUN apt-get update -yqq
RUN apt-get install -y git python3-pip postgresql-client-13 gunicorn procps netcat
RUN usermod -u ${HOST_USER_ID} ${INSTALL_USER}

USER ${INSTALL_USER}

# Clean up default installed Python packages
RUN python -m pip install --upgrade pip
RUN pip cache purge

# Install dependencies for all projects
{% for package in config.python_packages %}
{% if package.name == 'observatory-api' %}
# Set working directory for {{ package.name }}
ARG WORKING_DIR=/opt/{{ package.name }}
WORKDIR ${WORKING_DIR}

# Change owner of directory to airflow
USER root
RUN chown -R ${INSTALL_USER} ${WORKING_DIR}
USER ${INSTALL_USER}

{% with install_deps=true %}
  {% include 'Dockerfile.package_install.jinja2' %}
{% endwith %}

# Set working directory back to airflow home
WORKDIR ${OBSERVATORY_HOME}
{% endif %}
{% endfor %}

# Copy entry point scripts which install new dependencies at runtime and the Observatory Platform Python package
USER root

COPY entrypoint-api.sh /entrypoint-api.sh
RUN chmod +x /entrypoint-api.sh

RUN chown -R ${INSTALL_USER} /opt/observatory

USER ${INSTALL_USER}
ENTRYPOINT ["/entrypoint-api.sh"]
