# Copyright 2020 Curtin University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: James Diprose

FROM apache/airflow:1.10.12-python3.7

ARG HOST_USER_ID
ARG HOST_GROUP_ID
ARG OBSERVATORY_HOME=/opt/observatory

# Install git which is required when installing dependencies with pip
USER root
RUN apt-get update -yqq && apt-get install git build-essential pigz mawk unzip -y

# Change airflow user's user id to the hosts user id
RUN usermod -u ${HOST_USER_ID} airflow

# Change airflow user's group id to the hosts group id
RUN groupmod -g ${HOST_GROUP_ID} airflow

# Install Python dependencies for Observatory Platform as airflow user
USER airflow

{% if observatory.type.value == 'editable' -%}
# Install observatory-platform dependencies. The package itself will be installed at runtime after the directory
# is mounted.

# Set working directory to observatory-platform
ARG WORKING_DIR=${OBSERVATORY_HOME}/observatory-platform
WORKDIR ${WORKING_DIR}

# Install observatory platform dependencies
COPY ./requirements.txt requirements.txt
RUN pip3 install -r requirements.txt --user

{% else %}

# Install observatory-platform from PyPI
RUN pip3 install {{ observatory.versioned_package_name }} --user

{% endif %}

# Install DAGs projects and their dependencies.
{% for project in config.dags_projects %}
{% if project.type.value == 'editable' -%}
# Install {{ project.package_name }} dependencies. The package itself will be installed at runtime after the directory
# is mounted.

# Set working directory for {{ project.package_name }}
ARG WORKING_DIR=/opt/{{ project.package_name }}
WORKDIR ${WORKING_DIR}

# Change owner of directory to airflow
USER root
RUN chown -R airflow:airflow ${WORKING_DIR}
USER airflow

# Copy requirements file for {{ project.package_name }} and install
COPY ./requirements.{{ project.package_name }}.txt requirements.txt
# Remove first line as this is observatory-platform
RUN sed -i '1d' requirements.txt
RUN pip3 install -r requirements.txt --user

{% else %}

# Install {{ project.package_name }} from PyPI
RUN pip3 install {{ project.versioned_package_name }} --user

{% endif %}
{% endfor %}

# Set working directory to airflow home
WORKDIR ${AIRFLOW_HOME}

# Copy entry point scripts which install new dependencies at runtime and the Observatory Platform Python package
USER root
COPY entrypoint-root.sh /entrypoint-root.sh
COPY entrypoint-airflow.sh /entrypoint-airflow.sh
RUN chmod +x /entrypoint-root.sh
RUN chmod +x /entrypoint-airflow.sh

ENTRYPOINT ["/entrypoint-root.sh"]