repos:
-   repo: local
    hooks:
      - id: add-jira-id
        name: Add Jira ID from branch name
        description: Finds Jira ID from branch name and adds as prefix to commit message
        entry: ./bin/prefix_commit_jira.sh
        language: script
        stages: [prepare-commit-msg]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^(observatory-api/observatory/api/client|observatory-platform/observatory/platform/airflow)
        args: [--line-length=120]
