version: "3.8"
# POSTGRES_PASSWORD needs to be URL quoted
x-airflow-environment: &airflow-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgres://airflow:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:5432/airflow"
  AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
  AIRFLOW__CORE__AIRFLOW_HOME: "/opt/airflow/"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__CELERY__BROKER_URL: "redis://:@redis:6379/0"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:5432/airflow"

services:
  redis:
    image: "redis:6.0.5"
    restart: always
    ports:
      - 6379:6379

  flower:
    image: apache/airflow:1.10.10
    restart: always
    depends_on:
      - redis
    environment:
      <<: *airflow-env
    ports:
      - 5555:5555
    command: flower

  init_db:
    image: apache/airflow:1.10.10
    environment:
      <<: *airflow-env
    volumes:
      - "./dags:/opt/airflow/dags"
    entrypoint: /bin/bash
    command: >
      -c "airflow list_users || (airflow initdb
      && airflow create_user --role Admin --username airflow --password airflow -e airflow@airflow.com -f airflow -l airflow)"
    restart: on-failure

  webserver:
    image: apache/airflow:1.10.10
    restart: always
    depends_on:
      - redis
    environment:
      <<: *airflow-env
    ports:
      - 8080:8080
    volumes:
      - "./dags:/opt/airflow/dags"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: apache/airflow:1.10.10
    restart: always
    depends_on:
      - webserver
    environment:
      <<: *airflow-env
    volumes:
      - "./dags:/opt/airflow/dags"
    command: scheduler

  worker_local:
    image: apache/airflow:1.10.10
    restart: always
    depends_on:
      - scheduler
    environment:
      <<: *airflow-env
    volumes:
      - "./dags:/opt/airflow/dags"
    command: worker -q default