version: '3.8'
services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow-webserver
    secrets:
      - google_application_credentials.json
      - config.yaml
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW_USER_HOME=/usr/local/airflow
      - POSTGRES_HOST=airflow-postgres
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=${HOST_FERNET_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials.json
      - CONFIG_PATH=/run/secrets/config.yaml
    volumes:
      - "${HOST_DAGS_PATH}:/usr/local/airflow/dags"
      - "${HOST_DATA_PATH}:/usr/local/airflow/.observatory/data"
      - "${HOST_PACKAGE_PATH}:/usr/local/airflow/academic-observatory"
    ports:
      - '${HOST_AIRFLOW_UI_PORT}:8080'
    restart: always