#!/usr/bin/env bash
# This script runs commands as the root user

# Make airflow user own everything in home directory
chown -R airflow:airflow ${AIRFLOW_HOME}

# Make airflow user own everything in observatory directory
chown -R airflow:airflow /opt/observatory

sudo --preserve-env=AIRFLOW_HOME,AIRFLOW__CORE__EXECUTOR,AIRFLOW__CORE__SQL_ALCHEMY_CONN,AIRFLOW__CORE__FERNET_KEY,\
AIRFLOW__CORE__AIRFLOW_HOME,AIRFLOW__CORE__AIRFLOW_HOME,AIRFLOW__CORE__LOAD_EXAMPLES,\
AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS,AIRFLOW__WEBSERVER__RBAC,AIRFLOW__CELERY__BROKER_URL,\
AIRFLOW__CELERY__RESULT_BACKEND,AIRFLOW__SECRETS__BACKEND,AIRFLOW__SECRETS__BACKEND_KWARGS,\
GOOGLE_APPLICATION_CREDENTIALS,AO_HOME,AIRFLOW_UI_USER_EMAIL,AIRFLOW_UI_USER_PASSWORD,\
AIRFLOW_CONN_MAG_RELEASES_TABLE,AIRFLOW_CONN_MAG_SNAPSHOTS_CONTAINER,AIRFLOW_CONN_CROSSREF,AIRFLOW_VAR_DATA_PATH,\
AIRFLOW_VAR_PROJECT_ID,AIRFLOW_VAR_DATA_LOCATION,AIRFLOW_VAR_DOWNLOAD_BUCKET_NAME,AIRFLOW_VAR_TRANSFORM_BUCKET_NAME,\
AIRFLOW_VAR_ENVIRONMENT --user airflow --set-home --login /entrypoint-airflow.sh "$@"
