swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: gateway-qjb5mfja7a-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://testcloudrun-qjb5mfja7a-uc.a.run.app
  protocol: h2
#info:
#  title: Sample API
#  description: 'Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.'
#  version: 0.1.9
paths:
  /query:
    get:
      operationId: query.search
      tags:
        - People
      summary: Perform an elasticsearch search query
      description: Perform an elasticsearch search query
      parameters:
        - in: query
          name: agg
          description: The aggregation level
          required: true
          enum:
            - author
            - country
            - funder
            - group
            - institution
            - publisher
          type: string
        - name: subset
          in: query
          description: The required subset
          required: true
          enum:
            - citations
            - collaborations
            - disciplines
            - events
            - funders
            - journals
            - oa-metrics
            - output-types
            - publishers
          type: string
        - name: from
          in: query
          description: Start date
          required: false
          format: date
          minLength: 0
          maxLength: 10
          type: string
        - name: to
          in: query
          description: End date
          required: false
          format: date
          minLength: 0
          maxLength: 10
          type: string
        - name: id
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: country
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: country_code
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: journal
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: name
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: region
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: subregion
          in: query
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        '200':
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
      produces:
        - application/json