# flake8: noqa

"""
    Observatory API

    The REST API for managing and accessing data from the Observatory Platform.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agent@observatory.academy
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from observatory.api.client.api_client import ApiClient

# import Configuration
from observatory.api.client.configuration import Configuration

# import exceptions
from observatory.api.client.exceptions import OpenApiException
from observatory.api.client.exceptions import ApiAttributeError
from observatory.api.client.exceptions import ApiTypeError
from observatory.api.client.exceptions import ApiValueError
from observatory.api.client.exceptions import ApiKeyError
from observatory.api.client.exceptions import ApiException
