globalProperties:
  apiTests: "true"
  modelTests: "true"
additionalProperties:
  generateSourceCodeOnly: "true"
  hideGenerationTimestamp: "true"
  library: urllib3
  packageName: observatory.api.client
  projectName: client
  pythonAttrNoneIfUnset: "true"
  useNose: "false"