# Copyright 2020 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use the official lightweight Python image.
# https://hub.docker.com/_/python

FROM python:3.9-slim

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME

# Install requirements
COPY requirements.txt ./
RUN /bin/bash -c "pip3 install --no-cache-dir -r requirements.txt"

# Install berglas
COPY --from=gcr.io/berglas/berglas:latest /bin/berglas /bin/berglas

COPY app ./

ENTRYPOINT ["/bin/berglas", "exec",  "--",  "gunicorn", "-b", "0.0.0.0:8080", "app:app"]